name: Automate your Wiki pages
author: Victor Santiago
description: |
  This actions sets one of repository folders (say ~/docs) as source for your 
  repository's Wiki page 

inputs:
  token:
    description: PAT or GITHUB_TOKEN
    required: true
  repository:
    description: Repository name
    required: true
  docs-folder:
    description: Docs folder
    required: true
  user-name:
    description: Git user.name. Used while pushing on Wiki's repo
    default: BOT
  user-mail: 
    description: Git user.email. Used while pusing on Wiki's repo
    default: bot@bot.com

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch_depth: 0

    - id: tstamp
      run: |
        echo "NOW=$( date +%s).wiki" >> GITHUB_OUTPUTS
      shell: bash

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: ${{ inputs.repository }}.wiki
        path: ${{ steps.temp.outputs.NOW }}.wiki
        token: ${{ inputs.token }}

    - name: Update
      working-directory: ${{ steps.temp.outputs.NOW }}.wiki
      run: |
        git config user.name ${{ inputs.user-name }}
        git config user.email ${{ inputs.user-email }}

        cp ../${{ inputs.docs-folder }}/* .

        git add --all
        git commit -m "docs: update wiki" --allow-empty
        git push --force
      shell: bash

brands:
  icon: archive
  color: purple
